
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Language;

/** CUP generated class containing symbol constants. */
public class TOK {
  /* terminals */
  public static final int TK_equ = 50;
  public static final int RW_switch = 13;
  public static final int TK_comma = 62;
  public static final int RW_pow = 9;
  public static final int RW_endl = 24;
  public static final int TK_notequ = 47;
  public static final int TK_rbrc = 59;
  public static final int RW_bool = 4;
  public static final int RW_str = 6;
  public static final int RW_break = 19;
  public static final int TK_lessequ = 48;
  public static final int RW_tolower = 25;
  public static final int TK_string = 33;
  public static final int RW_c_str = 31;
  public static final int RW_int = 2;
  public static final int RW_execute = 32;
  public static final int TK_dec = 38;
  public static final int RW_for = 17;
  public static final int RW_true = 7;
  public static final int TK_sub = 40;
  public static final int TK_equequ = 46;
  public static final int RW_while = 16;
  public static final int RW_length = 28;
  public static final int TK_colon = 63;
  public static final int TK_lbcs = 60;
  public static final int TK_or = 54;
  public static final int RW_void = 22;
  public static final int TK_lpar = 56;
  public static final int RW_false = 8;
  public static final int RW_do = 18;
  public static final int RW_else = 12;
  public static final int TK_double = 36;
  public static final int EOF = 0;
  public static final int RW_cout = 23;
  public static final int RW_round = 27;
  public static final int TK_more = 52;
  public static final int RW_continue = 20;
  public static final int error = 1;
  public static final int TK_int = 35;
  public static final int RW_new = 10;
  public static final int RW_double = 3;
  public static final int TK_mult = 43;
  public static final int TK_lbrc = 58;
  public static final int TK_not = 55;
  public static final int TK_and = 53;
  public static final int TK_char = 34;
  public static final int TK_semicolon = 64;
  public static final int RW_typeof = 29;
  public static final int TK_inc = 37;
  public static final int TK_div = 44;
  public static final int TK_less = 51;
  public static final int RW_default = 15;
  public static final int TK_rbcs = 61;
  public static final int TK_moreequ = 49;
  public static final int RW_char = 5;
  public static final int TK_rpar = 57;
  public static final int RW_return = 21;
  public static final int TK_add = 39;
  public static final int RW_toupper = 26;
  public static final int TK_mod = 45;
  public static final int TK_minus = 42;
  public static final int RW_if = 11;
  public static final int RW_case = 14;
  public static final int TK_plus = 41;
  public static final int RW_tostring = 30;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RW_int",
  "RW_double",
  "RW_bool",
  "RW_char",
  "RW_str",
  "RW_true",
  "RW_false",
  "RW_pow",
  "RW_new",
  "RW_if",
  "RW_else",
  "RW_switch",
  "RW_case",
  "RW_default",
  "RW_while",
  "RW_for",
  "RW_do",
  "RW_break",
  "RW_continue",
  "RW_return",
  "RW_void",
  "RW_cout",
  "RW_endl",
  "RW_tolower",
  "RW_toupper",
  "RW_round",
  "RW_length",
  "RW_typeof",
  "RW_tostring",
  "RW_c_str",
  "RW_execute",
  "TK_string",
  "TK_char",
  "TK_int",
  "TK_double",
  "TK_inc",
  "TK_dec",
  "TK_add",
  "TK_sub",
  "TK_plus",
  "TK_minus",
  "TK_mult",
  "TK_div",
  "TK_mod",
  "TK_equequ",
  "TK_notequ",
  "TK_lessequ",
  "TK_moreequ",
  "TK_equ",
  "TK_less",
  "TK_more",
  "TK_and",
  "TK_or",
  "TK_not",
  "TK_lpar",
  "TK_rpar",
  "TK_lbrc",
  "TK_rbrc",
  "TK_lbcs",
  "TK_rbcs",
  "TK_comma",
  "TK_colon",
  "TK_semicolon"
  };
}

